-- TEST DATA BASE--

CREATE DATABASE test; -- CREATE DATABASE
USE test; -- USE THAT DATABASE

-- CREATE TABLE
CREATE TABLE address( -- address TABLE
id INT,
house_number INT,
city VARCHAR(30),
postcode VARCHAR(7)
);
CREATE TABLE people(  -- people TABLE
id INT,
first_name VARCHAR(30),
last_name VARCHAR(30),
address_id INT
);

CREATE TABLE pets(
id INT,
name VARCHAR(30),
species VARCHAR(30),
owner_id int
);

-- ADD PRIMARY KEY
ALTER TABLE address  -- ADD PRIMARY KEY TO address TABLE
ADD PRIMARY KEY (id);
ALTER TABLE people  -- ADD PRIMARY KEY TO people TABLE
ADD PRIMARY  KEY (id);
ALTER TABLE pets -- ADD PRIMARY KEY TO pets TABLE 
ADD PRIMARY KEY (id);

-- REMOVE PRIMARY KEY FROM TABLE
ALTER TABLE address -- REMOVE PRIMARY KEY FROM address TABLE
DROP PRIMARY KEY;
ALTER TABLE people -- REMOVE PRIMARY KEY OF people TABLE
DROP PRIMARY KEY;
ALTER TABLE pets -- REMOVE RPIMARY KEY FROM pets TABLE
DROP PRIMARY KEY;

-- ADD FORIGEN KEY TO A TABLE
ALTER TABLE people
ADD CONSTRAINT FK_PeopleAddress
FOREIGN KEY (address_id) REFERENCES address(id);

-- DELETE A FROIGEN KEY FROM A TABLE
ALTER TABLE people
DROP FOREIGN KEY FK_PeopleAddress;

-- ADD UNIQUE CONSTRAINS TO COLUMN
ALTER TABLE people
ADD CONSTRAINT FK_CON UNIQUE (id);

-- DELETE UNIQUE CONSTRAINTS FROM A TABLE
ALTER TABLE people
DROP INDEX FK_CON ;

-- CHANGE COLUMN NAME
ALTER TABLE people
CHANGE `first_Name` `first_name` VARCHAR(30);

-- CHANGE DATATYPE OF COLUM
ALTER TABLE people
MODIFY `first_name` VARCHAR(30);

-- --------------------CHALLANGE -------------------------------
ALTER TABLE pets
ADD PRIMARY KEY (id) ;

ALTER TABLE pets
ADD CONSTRAINT CONST
FOREIGN KEY (owner_id) REFERENCES people(id) ;

ALTER TABLE people
ADD COLUMN email VARCHAR(30) ;

ALTER TABLE people
ADD CONSTRAINT CONST UNIQUE(email); 

describe people;

ALTER TABLE pets
change `name` `first_name` VARCHAR(30);

ALTER TABLE address
MODIFY postcode CHAR(7);

